spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:forumdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:rootroot}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        logging:
          level:
            org.springframework.boot.autoconfigure: DEBUG