spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/forumdb
    username: ${DB_USER:postgres}
    password: ${DB_PASS:rootroot}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

springdoc:
  swagger-ui:
    enabled: false